fit_hrf : False
constraints : None
u_sfs : [ 0.5,  1. ,  3. ,  6. , 12. , 18. ]
u_con : [ 0.25      ,  0.38962234,  0.60722228,  0.94634947,  1.47487559, 2.29857792,  3.58230926,  5.5829909 ,  8.70103197, 13.56046584, 21.13384187, 32.9368679 , 51.33175852, 80.]

#fitting tolerance
xtol: 0.00001
ftol: 0.00001
# set csf grids and bounds
fixed_grid_baseline : False
csf_bounds:
  width_r   : [0, 3]# NOW FOLLOWING CARLIEN [0,5]   # width_r
  sf0       : [0, 18]# NOW FOLLOWING CARLIEN [0,10]       # sf0
  maxC      : [0, 200]# NOW FOLLOWING CARLIEN [0,100]     # maxC
  width_l   : [0.448,0.448]# NOW FOLLOWING CARLIEN [0,5]   # width_l
  beta      : [0,1000]    # beta
  baseline  : [-100,100]    # baseline
grid_nr: 20

hrf: None
  # pars: [1,1,0]
  # deriv_bound: [0,10]
  # disp_bound: [0,0]

rsq_threshold: 0.1
TR: 1.5