# ***** FOR ALL MODELS 
fit_hrf : True
fixed_grid_baseline : False
# -> fitting tolerance
xtol: 0.0001
ftol: 0.0001


# FOR CSF
u_sfs : [ 0.5,  1. ,  3. ,  6. , 12. , 18. ]
u_con : [ 0.25      ,  0.38962234,  0.60722228,  0.94634947,  1.47487559, 2.29857792,  3.58230926,  5.5829909 ,  8.70103197, 13.56046584, 21.13384187, 32.9368679 , 51.33175852, 80.]
# set csf grids and bounds
csf_bounds:
  width_r   : [0, 3]# NOW FOLLOWING CARLIEN [0,5]   # width_r
  sf0       : [0, 6]# NOW FOLLOWING CARLIEN [0,10]       # sf0
  maxC      : [0, 200]# NOW FOLLOWING CARLIEN [0,100]     # maxC
  width_l   : [0.448,0.448]# NOW FOLLOWING CARLIEN [0,5]   # width_l
  beta      : [0,1000]    # beta
  baseline  : [-5,5]    # baseline
csf_grid_nr: 20




# FOR PRF
# space our pRF lives in
vf_extent: [-5, 5]
# screen settings
screen_size_cm: 39.3
screen_distance_cm: 196
#unit volume RFs
normalize_RFs: False
#DM size in pixels (n_pix x n_pix) (has to be divisor of 1080)
n_pix: 100
# set prf amplitude
bold_bsl: [-5,5]
prf_ampl: [0,1000]
css_exponent: [0.01,3]

# grids for normalization model (not used if model != norm)
use_previous_gaussian_fitter_hrf : True
norm:
  surround_amplitude_grid: [0.05,0.2,0.4,0.7,1,3]
  surround_size_grid: [5,8,12,18]
  neural_baseline_grid: [0,1,10,100]
  surround_baseline_grid: [0.1,1.0,10.0,100.0] # [1]
  surround_amplitude_bound: [0,1000]
  neural_baseline_bound: [0,1000]
  surround_baseline_bound: [0.000001,1000] # [1]

css:
  css_exponent_grid: [0.05,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1,1.1]
  css_exponent_bound: [0.01,3]

dog:
  dog_surround_amplitude_grid: [0.05,0.1,0.25,0.5,0.75,1,2]
  dog_surround_size_grid: [3,5,8,11,14,17,20,23,26]
  surround_amplitude_bound: [0,1000]

hrf:
  pars: [1,1,0]
  deriv_bound: [0,10]
  disp_bound: [0,0]

grid_nr: 20 # 20 OG 
rsq_threshold: 0.1
TR: 1.5